# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies Api
      run: dotnet restore
      working-directory: ./NotificationSystem.Api
      
    - name: Build Api
      run: dotnet build --no-restore
      working-directory: ./NotificationSystem.Api
      
    - name: Test Api
      run: dotnet test
      working-directory: ./NotificationSystem.Api.Tests
      
    - name: Restore dependencies Worker
      run: dotnet restore
      working-directory: ./NotificationSystem.Worker
      
    - name: Build Worker
      run: dotnet build --no-restore
      working-directory: ./NotificationSystem.Worker
      
    - name: Test Worker
      run: dotnet test
      working-directory: ./NotificationSystem.Worker.Tests


    
